version: '3.1'

services:

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: koshkas
      MONGO_INITDB_ROOT_PASSWORD: koshkas
    volumes: 
      - ./database/mongodbdata:/data/db
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: koshkas
      ME_CONFIG_MONGODB_ADMINPASSWORD: koshkas
    depends_on: 
      - mongo
  
  vkbot:
    build: vkbot/.
    depends_on:
      - mongo
    restart: on-failure
    volumes:
      - ./yaml/:/app/yaml/
      - ./vkbot/code/:/app/code/