version: '3.1'

services:

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: koshkas
      MONGO_INITDB_ROOT_PASSWORD: koshkas
    volumes: 
      - ./database/mongodbdata:/data/db
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: koshkas
      ME_CONFIG_MONGODB_ADMINPASSWORD: koshkas
    depends_on: 
      - mongo
  
  flask:
    build: server/.
    depends_on:
      - mongo
    ports:
     - "5000:5000"
    restart: on-failure
    volumes:
      - ./yaml/:/app/yaml/
      - ./server/code/:/app/code/
  
  telegram:
    build: telegram/.
    depends_on:
      - flask
    restart: on-failure
    volumes:
      - ./yaml/:/app/yaml/
      - ./telegram/code/:/app/code/